#!/bin/sh
cat <<CONFIG > ./dist/gon_sign.json
{
    "source" : ["./dist/macschema_darwin_amd64/macschema"],
    "bundle_id" : "com.progrium.macschema",
    "sign" :{
        "application_identity" : "Developer ID Application: Jeff Lindsay"
    }
}
CONFIG
gon -log-level=info -log-json ./dist/gon_sign.json > /dev/null
cat <<CONFIG > ./dist/gon_notarize.json
{
    "notarize": [{
        "path": "./dist/macschema_${1}.zip",
        "bundle_id": "com.progrium.macschema",
        "staple": false
    }]
}
CONFIG
